### PR TITLE
Fix; typo in authentication.py

### PR DESCRIPTION
**Pull request by karuso**
Fixed typo in authentication.py which resulted in a 500 error when passing a non existing token

### CODE REVIEW

**Comment by tng10** [comment]
I just had the same problem here.

@JamesRitchie what do you think about @karuso's PR? It sounds good for me.

**Comment by hieuh25** [comment]
Same problem and it's a critical one, please merge the PR.

**Comment by max-pfeiffer** [comment]
Please merge, it is a critical bug.

**Comment by JamesRitchie** [comment]
Fixed with #12

**Pull request closed without merging**
